config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles #, only: [:show, :index, :new, :create, :edit, :update, :destroy] #These are the REST-ful routes
end

app/models/application_record.rb
# frozen_string_literal: true

# here comes the documentation for ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  def show; end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new # Create a new instance of Article at the first page load so be able to use
  end

  def edit; end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article was deleted successfully."
    redirect_to articles_path
  end

  private # This is a private method that can only be called from within this class
    def set_article
      @article = Article.find(params[:id])
    end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

# Path: app/controllers/articles_controller.rb

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home; end

  def about; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2><%= t('errors_prohibited_this_article_from_being_saved') %></h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @article, local: true)   do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<%end %>

app/views/articles/edit.html.erb
<h1><%= t('edit_article') %></h1>

<%= render 'form' %>

<%= link_to 'Articles', articles_path %>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title%></td>
        <td><%= article.description%></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Delete', article_path(article), data:{
          turbo_method: :delete,
          turbo_confirm: 'Are you sure?'
        } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to 'Home', root_path %></p>
<p><%=link_to 'Create new article', new_article_path %></p>

app/views/articles/new.html.erb
<h1><%= t('create_a_new_article') %></h1>

<%= render 'form' %>

<%= link_to 'Home', articles_path %>

app/views/articles/show.html.erb
<h1>This is the show articles page...</h1>

<p><strong>Title:</strong> <%= @article.title%></p>
<p><strong>Description:</strong> <%= @article.description%></p>
<%= link_to 'Edit', edit_article_path(@article) %>
<%= button_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %>
<%= link_to 'Articles', articles_path %>

app/views/layouts/_footer.html.erb
<div class="container fixed-bottom">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="mb-3 mb-md-0 text-muted">© 2022 Company, Inc</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><i class="bi bi-twitter"></i></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><i class="bi bi-facebook"></i></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><i class="bi bi-instagram"></i></svg></a></li>
    </ul>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-dark bg-dark navbar-expand-lg">
  <div class="container-fluid">
    <%= link_to "ALPHA BLOG", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "articles", articles_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "turbo", type: "module" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <%= yield %>
  <%= render 'layouts/footer' %>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= t('about') %></h1>


<%= link_to t('articles'), articles_path %>
<%= link_to t('home'), root_path %>

app/views/pages/home.html.erb
<div class="mt-5 container text-center">
  <div class="p-5 mb-4 bg-body-tertiary rounded-3">
    <div class="container-fluid py-5">
      <h1 class="display-5 fw-bold">Alpha blog</h1>
      <p class="fs-4">This is my first webapp written in ruby. Ruby on rails. I have to continue, even if i feel tired, because i need to earn more money so be able to improve. :-)</p>
      <button class="btn btn-primary btn-lg" type="button">Example button <i class="bi bi-house"></i></button>
    </div>
  </div>
</div>